In [148]:
import pandas as pd
import numpy as np

In [149]:
pop_by_zip = pd.read_csv('data/population_by_zip_2010.csv')

In [150]:
us_postal_codes = pd.read_csv('data/us_postal_codes.csv')

In [151]:
popzip = pop_by_zip.groupby('zipcode')['population'].sum().reset_index(name="popsum")
popzip.head(20)

    zipcode  popsum
0       602  108502
1       603  117092
2       606   10579
3       610   34457
4       612   67536
5       616   17856
6       617   67305
7       622   13479
8       623  112168
9       624   73020
10      627   90031
11      631    2103
12      637   67016
13      638   40337
14      641   54112
15      646   80856
16      647    4012
17      650   39112
18      652   12024
19      653   28699

In [152]:
temp = us_postal_codes.merge(popzip,how='outer',on='zipcode')

In [153]:
temp = temp.dropna()
us_postal_codes = temp
us_postal_codes

       zipcode             city state   popsum
2         1001           Agawam    MA  20545.0
3         1002          Amherst    MA  33219.0
4         1003          Amherst    MA  23661.0
6         1005            Barre    MA   8151.0
7         1007      Belchertown    MA  30796.0
8         1008        Blandford    MA   1028.0
9         1009       Bondsville    MA   1977.0
10        1010        Brimfield    MA   6093.0
11        1011          Chester    MA   3571.0
12        1012     Chesterfield    MA   1717.0
13        1013         Chicopee    MA  24405.0
15        1020         Chicopee    MA  80009.0
17        1022         Chicopee    MA   4147.0
18        1026       Cummington    MA   1642.0
19        1027      Easthampton    MA  36853.0
20        1028  East Longmeadow    MA  41228.0
21        1029        East Otis    MA   1336.0
22        1030    Feeding Hills    MA  30695.0
23        1031     Gilbertville    MA   2943.0
24        1032           Goshen    MA   1474.0
25        1033           Granby    MA   6593.0
26        1034        Granville    MA   3464.0
27        1035           Hadley    MA   8648.0
28        1036          Hampden    MA  13107.0
29        1037         Hardwick    MA   2174.0
30        1038         Hatfield    MA   6496.0
31        1039      Haydenville    MA   2892.0
32        1040          Holyoke    MA  87089.0
34        1050       Huntington    MA   2077.0
35        1053            Leeds    MA   3813.0
...        ...              ...   ...      ...
40895    99786           Ambler    AK    303.0
40896    99788      Chalkyitsik    AK    108.0
40897    99789          Nuiqsut    AK    676.0
40898    99790        Fairbanks    AK     13.0
40899    99791          Atqasuk    AK    498.0
40900    99801           Juneau    AK  76201.0
40905    99820           Angoon    AK    815.0
40907    99824          Douglas    AK   3419.0
40908    99825       Elfin Cove    AK    233.0
40909    99826         Gustavus    AK    943.0
40910    99827           Haines    AK   2725.0
40911    99829           Hoonah    AK    562.0
40912    99830             Kake    AK    336.0
40913    99832          Pelican    AK    105.0
40914    99833       Petersburg    AK   1978.0
40915    99835            Sitka    AK  14993.0
40916    99836   Port Alexander    AK     50.0
40917    99840          Skagway    AK   2364.0
40918    99841  Tenakee Springs    AK    262.0
40920    99901        Ketchikan    AK  35580.0
40921    99903     Meyers Chuck    AK     38.0
40922    99918     Coffman Cove    AK    540.0
40923    99919       Thorne Bay    AK   1226.0
40924    99921            Craig    AK   2101.0
40925    99922         Hydaburg    AK    765.0
40926    99923            Hyder    AK    199.0
40927    99925          Klawock    AK    802.0
40928    99926       Metlakatla    AK   3807.0
40929    99927      Point Baker    AK    159.0
40931    99929         Wrangell    AK   5217.0

[32972 rows x 4 columns]

In [154]:
us_postal_codes.columns

Index(['zipcode', 'city', 'state', 'popsum'], dtype='object')

In [155]:
population = us_postal_codes.groupby(['city','state'])['popsum'].sum().reset_index(name="pop")
population.head(100)

                       city state       pop
0                Aaronsburg    PA    2781.0
1                 Abbeville    AL   14551.0
2                 Abbeville    GA   13033.0
3                 Abbeville    LA   49948.0
4                 Abbeville    MS    2537.0
5                 Abbeville    SC   19096.0
6                     Abbot    ME    1201.0
7                Abbotsford    WI    3257.0
8                    Abbott    TX    2848.0
9               Abbottstown    PA    6660.0
10                Abbyville    KS     322.0
11                    Abell    MD     940.0
12              Abercrombie    ND     119.0
13                 Aberdeen    ID    8937.0
14                 Aberdeen    MD   45831.0
15                 Aberdeen    MS   31221.0
16                 Aberdeen    NC   19934.0
17                 Aberdeen    OH    2994.0
18                 Aberdeen    SD   65012.0
19                 Aberdeen    WA   29267.0
20  Aberdeen Proving Ground    MD    4192.0
21                Abernathy    TX    5743.0
22                     Abie    NE     175.0
23                  Abilene    KS   27691.0
24                  Abilene    TX  237188.0
25                 Abingdon    IL    6256.0
26                 Abingdon    MD   49217.0
27                 Abingdon    VA   40793.0
28                 Abington    MA   42154.0
29                 Abington    PA   37339.0
..                      ...   ...       ...
70                     Adak    AK     863.0
71                  Adamant    VT     185.0
72                    Adams    KY     494.0
73                    Adams    MA   13905.0
74                    Adams    MN    3864.0
75                    Adams    ND     665.0
76                    Adams    NE     813.0
77                    Adams    NY    5334.0
78                    Adams    OK     402.0
79                    Adams    OR    1778.0
80                    Adams    TN    9342.0
81                    Adams    WI    7458.0
82             Adams Center    NY    5879.0
83                Adams Run    SC    3740.0
84                Adamsburg    PA     283.0
85                Adamstown    MD    9662.0
86                Adamstown    PA    2245.0
87               Adamsville    AL   13127.0
88               Adamsville    OH    1337.0
89               Adamsville    PA     711.0
90               Adamsville    TN   10589.0
91               Addieville    IL    2027.0
92                Addington    OK     337.0
93                    Addis    LA    7902.0
94                  Addison    AL    4168.0
95                  Addison    IL   51632.0
96                  Addison    ME    2719.0
97                  Addison    MI    2494.0
98                  Addison    NY   12193.0
99                  Addison    PA     669.0

[100 rows x 3 columns]

In [156]:
population.to_csv('data/population.csv')