In [33]:
import pandas as pd
import numpy as np
import math
from datetime import datetime
from sklearn.linear_model import LinearRegression

In [34]:
# US Sample data
fulldata = pd.read_csv('data/Preprocessed.csv')

In [40]:
fulldata.shape

(14154437, 24)

In [43]:
# Generate Days Posted for each listing
df = fulldata
def get_diff(df):
    start = df['date'].min()
    end = df['date'].max()
    end_day = datetime.strptime(end, '%Y-%m-%d')
    start_day = datetime.strptime(start, '%Y-%m-%d')
    return (end_day-start_day).days + 1

listings = df.groupby(['stateProvince','city','jobId'])
dates = listings.apply(get_diff).reset_index(name="DaysPosted")
dates.shape
dates
# print("Finished calculating")
# dates.set_index('jobId')
# df.set_index('jobId')
# dates = dates.join(df, how='inner', lsuffix='_left', rsuffix='_right')
# print("Finished joining")
# city_listings = dates.groupby(['stateProvince', 'city'])['DaysPosted'].mean().reset_index(name='AvgDays')
# print("Finished aggregating")
# city_listings.head(20)

ValueError: No axis named city for object type <class 'pandas.core.frame.DataFrame'>

In [42]:
dates

             jobId  DaysPosted
0       job0000000           3
1       job0000001           5
2       job0000002           3
3       job0000003          13
4       job0000005          18
5       job0000006          19
6       job0000010          28
7       job0000015          35
8       job0000016          35
9       job0000017          36
10      job0000019           1
11      job0000021          35
12      job0000022           4
13      job0000024          55
14      job0000025          53
15      job0000026          26
16      job0000027          55
17      job0000028          58
18      job0000029          19
19      job0000030           1
20      job0000032          11
21      job0000033          60
22      job0000034          39
23      job0000035          11
24      job0000036           3
25      job0000037          61
26      job0000040          59
27      job0000042          12
28      job0000043          27
29      job0000044          59
...            ...         ...
858554  job1082868           1
858555  job1082869           1
858556  job1082871           1
858557  job1082872           1
858558  job1082873           1
858559  job1082874           1
858560  job1082877           1
858561  job1082878           1
858562  job1082879           1
858563  job1082880           1
858564  job1082881           1
858565  job1082882           1
858566  job1082884           1
858567  job1082887           1
858568  job1082888           1
858569  job1082890           1
858570  job1082891           1
858571  job1082892           1
858572  job1082893           1
858573  job1082895           1
858574  job1082896           1
858575  job1082898           1
858576  job1082899           1
858577  job1082900           1
858578  job1082901           1
858579  job1082902           1
858580  job1082903           1
858581  job1082904           1
858582  job1082905           1
858583  job1082907           1

[858584 rows x 2 columns]

In [39]:
city_listings.shape

(15873, 3)

In [9]:
city_listings.to_csv('data/listing_time.csv')
print("Finished writing to csv")

Finished writing to csv

In [90]:
# Regression
lm = LinearRegression(n_jobs=-1)
independent = df[['']]

KeyError: ('clicks', 'occurred at index Unnamed: 0')